version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
      - file

hooks:
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 60
      runas: ec2-user
