version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    exclude:
      - appspec.yml

permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: deploy-scripts/cleanup.sh
      runas: ec2-user
  ApplicationStart:
    - location: deploy-scripts/application-start-hook.sh
      timeout: 60
      runas: ec2-user
  ApplicationStop:
    - location: deploy-scripts/application-stop-hook.sh
      timeout: 60
      runas: ec2-user
