version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Install phase"

  build:
    commands:
      - echo "Build started"
      - ls -al ..
      - bash ../gradlew build -x test

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
