version: 0.2

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew build -x test

artifacts:
  files:
    - build/libs/*.jar
    - appspec.yml
    - deploy-scripts/**/*
cache:
  paths:
    - node_modules/**/*
