version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - chmod +x gradlew

  pre_build:
    commands:
      - echo "Pre-build phase"
      - ./gradlew clean

  build:
    commands:
      - echo "Build started on `date`"
      - ./gradlew build -x test

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
